import AsyncStorage from '@react-native-async-storage/async-storage';

const JWT_KEY = 'USER_JWT';

interface JWTPayload {
  user: string;
  timestamp: number;
}

/**
 * Simple JWT generator for demo purposes
 * In production, this would be generated by a backend service
 */
export const generateJWT = (): string => {
  const payload: JWTPayload = {
    user: 'guest',
    timestamp: Date.now(),
  };
  
  // Simple base64 encoding for demo purposes
  // In production, use a proper JWT library with signing
  const header = btoa(JSON.stringify({ alg: 'none', typ: 'JWT' }));
  const body = btoa(JSON.stringify(payload));
  
  return `${header}.${body}.demo`;
};

/**
 * Store JWT in AsyncStorage
 */
export const storeJWT = async (token: string): Promise<void> => {
  try {
    await AsyncStorage.setItem(JWT_KEY, token);
  } catch (error) {
    console.error('Error storing JWT:', error);
    throw error;
  }
};

/**
 * Retrieve JWT from AsyncStorage
 */
export const getJWT = async (): Promise<string | null> => {
  try {
    return await AsyncStorage.getItem(JWT_KEY);
  } catch (error) {
    console.error('Error retrieving JWT:', error);
    return null;
  }
};

/**
 * Remove JWT from AsyncStorage (logout)
 */
export const removeJWT = async (): Promise<void> => {
  try {
    await AsyncStorage.removeItem(JWT_KEY);
  } catch (error) {
    console.error('Error removing JWT:', error);
    throw error;
  }
};

/**
 * Check if user is authenticated
 */
export const isAuthenticated = async (): Promise<boolean> => {
  const token = await getJWT();
  return token !== null;
};

